"use strict";
const assert = require("node:assert/strict");
const { spawn } = require("node:child_process");
const fs = require("node:fs");
const os = require("node:os");
const path = require("node:path");
const { DatabaseSync } = require("node:sqlite");
const { createInspection, gradeInspection } = require("./inspection");
const { workplaceBenefits, npcFit, negotiate, requiredSkillLevel } = require("./progression");
const { repairQuote, repairReliability, inspectionQuote, careerProgress } = require("./gameplay");

async function run() {
  assert.equal(requiredSkillLevel(4), 3);
  assert.equal(workplaceBenefits({ ownedAssets: [{ propertyRole: "workshop", rentalStatus: "rented" }] }).repair, 0);
  assert.equal(workplaceBenefits({ ownedAssets: [{ propertyRole: "workshop", rentalStatus: "workplace", workplaceLevel: 3, maintenance: 50 }] }).repair, .05);
  const testCar = { year: 2020, defects: [{ repaired: true, repairReliability: 60 }], upgrades: ["sport"] };
  const upgrades = [{ key: "sport", profile: "sport" }];
  assert.ok(npcFit(testCar, { type: "specialist" }, upgrades).multiplier > npcFit(testCar, { type: "endBuyer" }, upgrades).multiplier);
  assert.equal(negotiate({ amount: 104000, current: 100000, ceiling: 120000 }).accepted, false);
  assert.equal(negotiate({ amount: 104000, current: 100000, ceiling: 120000, skill: 2 }).accepted, true);
  assert.equal(negotiate({ amount: 200000, current: 100000, ceiling: 120000, attempts: 1 }).exhausted, true);
  for (const category of ["engine", "chassis", "body", "electrics", "tires", "documents"]) {
    const game = createInspection(category);
    const perfect = game.rounds.map(round => round.target ?? round.answer);
    assert.equal(gradeInspection(game, perfect).accuracy, 100);
    assert.equal(gradeInspection(game, [-1000, -1000, -1000]).bonus, 0);
    assert.throws(() => gradeInspection(game, [null, null, null]));
    assert.throws(() => gradeInspection(game, []));
  }
  assert.throws(() => repairQuote({ labor: 1000, plan: "unknown" }));
  assert.equal(careerProgress({ cash: 100000000 }).stage, "Новичок");
  assert.equal(careerProgress({ deals: 5, profit: 150000, reputation: { score: 50 } }).stage, "Гаражный мастер");
  assert.throws(() => inspectionQuote("unknown", 0, 0));
  assert.equal(repairReliability("restoration", 68, 50), 34);
  assert.equal(inspectionQuote("visual", 0, 0).depth, 1);
  assert.equal(inspectionQuote("instrumental", 0, 0).depth, 4);
  assert.equal(inspectionQuote("instrumental", 5, 3).confidence, 100);
  assert.ok(repairQuote({ labor: 10000, plan: "restoration" }).total > repairQuote({ labor: 10000 }).total);
  const directory = fs.mkdtempSync(path.join(os.tmpdir(), "market-gameplay-"));
  const port = 5100 + process.pid % 500;
  let server;
  const start = async () => {
    server = spawn(process.execPath, ["server.js"], { cwd: __dirname, env: { ...process.env, PORT: String(port), PEREKUP_DATA_DIR: directory }, stdio: ["ignore", "pipe", "pipe"] });
    return new Promise((resolve, reject) => {
      const timeout = setTimeout(() => reject(Error("Server timeout")), 15000);
      server.once("error", reject);
      server.stdout.on("data", (data) => { if (String(data).includes("Perekup Market")) { clearTimeout(timeout); resolve(); } });
    });
  };
  const stop = () => new Promise((resolve) => { if (!server || server.exitCode !== null) return resolve(); server.once("exit", resolve); server.kill(); });
  try {
    await start();
    let token;
    const request = async (url, body, expected = 200) => {
      const response = await fetch(`http://127.0.0.1:${port}${url}`, { method: body ? "POST" : "GET", headers: { "Content-Type": "application/json", ...(token ? { Authorization: `Bearer ${token}` } : {}) }, ...(body ? { body: JSON.stringify(body) } : {}) });
      const result = await response.json();
      assert.equal(response.status, expected, JSON.stringify(result.error));
      return result;
    };
    let state = await request("/api/join", { name: `Check${Date.now().toString().slice(-8)}` });
    token = state.token;
    const candidate = state.market.filter((car) => car.saleType !== "auction" && car.price < 400000).sort((a,b) => a.price-b.price)[0];
    assert.ok(candidate, "Affordable vehicle exists");
    state = await request("/api/buy", { carId: candidate.id });
    assert.ok(state.player.achievements.unlocked.includes("first_purchase"));
    const xp = state.player.xp;
    assert.equal((await request("/api/state")).player.xp, xp, "Reading state must not grant rewards");
    state = await request("/api/check", { carId: candidate.id, category: "engine", method: "visual", interactionScore: 100 });
    assert.equal(state.checkResult.confidence, 17, "Client score cannot override diagnostic depth");
    await request("/api/check", { carId: candidate.id, category: "engine", method: "visual" }, 400);
    const challenge = await request("/api/inspection/start", { carId: candidate.id, category: "engine", method: "visual" });
    const submission = { carId: candidate.id, category: "engine", method: "visual", challengeId: challenge.challengeId, answers: challenge.rounds.map(round => round.target) };
    await request("/api/check", { ...submission, category: "body" }, 400);
    state = await request("/api/check", submission);
    assert.equal(state.checkResult.confidence, 50);
    await request("/api/check", submission, 400);
    const before = state.player.cash;
    state = await request("/api/check", { carId: candidate.id, category: "engine", method: "instrumental" });
    assert.equal(before-state.player.cash, 9000);
    state = await request("/api/service-diagnostic", { carId: candidate.id });
    const defect = state.player.garage[0].defects.filter((d) => !d.repaired).sort((a,b) => a.serviceRepairCost-b.serviceRepairCost)[0];
    assert.ok(defect.servicePlans.length === 3);
    const quote = defect.servicePlans.find((p) => p.key === "restoration");
    const cash = state.player.cash;
    await request("/api/repair", { carId: candidate.id, defect: defect.code, plan: "invalid" }, 400);
    if (cash >= quote.total) {
      state = await request("/api/repair", { carId: candidate.id, defect: defect.code, mode: "workshop", plan: "restoration" });
      assert.equal(cash-state.player.cash, quote.total, "Displayed repair quote must match charge");
      assert.equal(state.player.garage[0].defects.find((d) => d.code === defect.code).repairQuality, "Восстановление");
    } else throw Error("Test vehicle repair exceeds budget");
    const expectedPlayer = state.player;
    await stop();
    await start();
    state = await request("/api/state");
    assert.equal(state.player.cash, expectedPlayer.cash);
    assert.equal(state.player.xp, expectedPlayer.xp);
    assert.deepEqual(state.player.achievements, expectedPlayer.achievements);
    const persistentDefects = defects => defects.map(defect => ({ ...defect, servicePlans: defect.servicePlans.map(({ forecastLow, forecastHigh, projectedProfit, ...plan }) => plan) }));
    assert.deepEqual(persistentDefects(state.player.garage[0].defects), persistentDefects(expectedPlayer.garage[0].defects));
    await stop();
    const database = new DatabaseSync(path.join(directory, "game.db"));
    const saved = JSON.parse(database.prepare("SELECT payload FROM game_state WHERE id = 1").get().payload);
    const fixture = saved.players.find(([, player]) => player.id === state.player.id)[1];
    fixture.cash = 10000000; fixture.skillPoints = 20;
    const npcLot = structuredClone(fixture.garage[0]);
    Object.assign(npcLot, { id: "qa_npc_lot", sellerId: fixture.id, ownerId: null, seller: fixture.name, saleType: "fixed", price: 500000, description: "Осмотр выполнен, состояние отражено в истории" });
    saved.market.push(npcLot);
    saved.offers.push(["qa_npc_offer", { id: "qa_npc_offer", carId: npcLot.id, sellerId: fixture.id, buyerId: "bot_igor", buyerName: "Игорь с сервиса", buyerType: "bot", amount: 10000, status: "active", attempts: 0 }]);
    fixture.ownedAssets.push({ id: "qa_workshop", key: "garage_block", name: "Test workshop", type: "property", propertyRole: "workshop", income: 74000, purchasePrice: 1000000, fairValue: 1000000, maintenance: 100, rentalStatus: "vacant", incomeLastAt: Date.now(), taxLastAt: Date.now() });
    database.prepare("UPDATE game_state SET payload = ?, updated_at = ? WHERE id = 1").run(JSON.stringify(saved), Date.now()); database.close();
    await start();
    await request("/api/skill", { skill: "negotiation" }, 400);
    state = await request("/api/skill", { skill: "appraisal" });
    state = await request("/api/skill", { skill: "negotiation" });
    assert.equal(state.player.skills.negotiation, 1);
    const negotiationState = await request("/api/offer/respond", { offerId: "qa_npc_offer", action: "counter", amount: 400000 });
    const refused = negotiationState.player.incomingOffers.find(offer => offer.id === "qa_npc_offer");
    assert.ok(refused && refused.attempts === 1 && refused.relationship < 0, "Rejected negotiation must consume patience and trust");
    const successful = await request("/api/offer/respond", { offerId: "qa_npc_offer", action: "counter", amount: 10100 });
    assert.ok(!successful.market.some(car => car.id === "qa_npc_lot"), "Accepted NPC counteroffer must sell the vehicle");
    assert.equal(successful.player.deals, 1);
    state = successful;
    const points = state.player.skillPoints + Object.values(state.player.skills).reduce((sum, level) => sum + level, 0);
    state = await request("/api/skill/reset", {});
    assert.equal(state.player.skillPoints, points);
    assert.ok(Object.values(state.player.skills).every(level => level === 0));
    await request("/api/skill/reset", {}, 400);
    state = await request("/api/property/manage", { assetId: "qa_workshop", action: "workplace" });
    assert.equal(state.player.ownedAssets.find(asset => asset.id === "qa_workshop").rentalStatus, "workplace");
    const assetBefore = state.player.ownedAssets.find(asset => asset.id === "qa_workshop");
    const cashBeforeUpgrade = state.player.cash;
    state = await request("/api/property/manage", { assetId: "qa_workshop", action: "upgrade" });
    assert.equal(cashBeforeUpgrade - state.player.cash, assetBefore.incomeState.upgradeCost);
    assert.equal(state.player.ownedAssets.find(asset => asset.id === "qa_workshop").workplaceLevel, 1);
    assert.equal(state.player.ownedAssets.find(asset => asset.id === "qa_workshop").incomeState.perCycle, 0);
    const upgrade = state.player.garage[0].upgradeOptions.find(item => !item.installed);
    const cashBeforeTuning = state.player.cash;
    state = await request("/api/car/upgrade", { carId: candidate.id, upgrade: upgrade.key });
    assert.equal(cashBeforeTuning - state.player.cash, upgrade.serviceCost);
    await request("/api/car/upgrade", { carId: candidate.id, upgrade: upgrade.key }, 400);
    await stop(); await start(); state = await request("/api/state");
    assert.equal(state.player.ownedAssets.find(asset => asset.id === "qa_workshop").workplaceLevel, 1);
    assert.ok(state.player.garage[0].upgradeOptions.find(item => item.key === upgrade.key).installed);
    assert.equal(state.player.skills.negotiation, 0);
    console.log("PASS: inspection sessions, NPC responses, skills/reset, workplace upgrades, tuning prices, repair quotes and persistence");
  } finally {
    await stop();
  }
}
run().catch((error) => { console.error(error); process.exitCode = 1; });
